### ISSUE TITLE
How to run a dev server

### ISSUE THREAD

**Issue by thoragio** [BenoitZugmeyer/leviathan#1]
Hi - I cloned the repo, ran `npm i` to install dependencies and then ran `npm run build`. I had to upgrade openssl to get access to sha-256, then in the build script add the `-e` flag to `sed` (an OS X thing), but after those two tweaks I managed to create a build.

My question is what is the best way to run a dev server for the app? I've mainly use create-react-app or next.js, so all of the dev config is done automatically. Would you mind adding the dev config to the repo?

I started working on my own Mastodon client but I like what you have done so far so I would prefer to build on top of it rather than just hacking away on my own implementation (which is less elegant than yours). I learned some new stuff by looking at your code, so thanks for posting it here.

**Comment by thoragio** [comment]
I figured out that I needed to run the /bin/dev-server script with node. I installed node 7.9.0 since the async function was not working with v6 of node. So when I run `node bin/devserver` I get the following error:

```
Temporary directory: /Users/thoragio/code/leviathan/tmp-leviathan-bY9ntU
Listen: localhost:8080
Upstreams:
  /	/Users/thoragio/code/leviathan/

Generating certificates...
Launching HTTP server (use ^C to quit)...
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn nginx ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

I'm guessing I need to install nginx on my machine. I'll try that next when I have some more time later today.

**Comment by theChesCat** [comment]
Asking myself the same question as @thoragio

**Comment by BenoitZugmeyer** [comment]
Hi, thank you for your interest! Please know that this project is just a start and you can't do much with it right now.

I should remove the `bin/dev-server` script as it isn't needed: just serve the `dist` server with any commandline dev server and it should work:
* with python 2 : `cd dist && python2 -m SimpleHTTPServer`
* with python 3 : `cd dist && python -m http.server`
* with php : `cd dist && php -S localhost:8000`
* if you want to stick with nodejs, you can use `http-server` (`npm install http-server`)

Also if you want to rebuild things when developping, you can watch for changes with `$(npm bin)/rollup -c -w`

**Comment by thoragio** [comment]
Thanks @BenoitZugmeyer. Running it with live-server (node) works great.

@theChesCat Here's what my bin/build file looks like now:

```
#!/bin/bash

set -euo pipefail

BIN="$(npm bin)"

cd $(dirname $0)/..
rm -rf dist
mkdir dist

cp -r assets/* dist

"$BIN"/rollup -c
"$BIN"/babili dist/index.js -o dist/index.js
hash=$(/usr/local/opt/openssl/bin/openssl sha256 dist/index.js | tail -c 65)
sed -i -e "s/BUNDLE_NAME/index.js?$hash/" dist/index.html
"$BIN"/rollup -c -w
```

And here's how it diffs from the original:

```
-hash=$(openssl sha256 dist/index.js | tail -c 65)
-sed -i "s/BUNDLE_NAME/index.js?$hash/" dist/index.html
+hash=$(/usr/local/opt/openssl/bin/openssl sha256 dist/index.js | tail -c 65)
+sed -i -e "s/BUNDLE_NAME/index.js?$hash/" dist/index.html
+"$BIN"/rollup -c -w
```

Note that the full path for openssl is a bit of a hack on my side because I don't want to rewrite the path for everything in case it breaks anything else relying on the older version of openssl that is still installed by default in OS X.

**Comment by theChesCat** [comment]
Thanks a lot for taking the time to post your code @thoragio !
Clever thing to directly set the path for the new openssl version in the /bin/build file, I'm on OS X too so I was facing the same issue.

**Comment by BenoitZugmeyer** [comment]
I commited a new bin/build implementation in full nodejs, hopefully solving your issues.

Just run `npm run dev` and it will:
* build
* serve on port 10001
* watch for change and rebuild + reload

**Comment by theChesCat** [comment]
Thanks a lot!

**Comment by thoragio** [comment]
Thank you. Much appreciated.

**Comment by BenoitZugmeyer** [comment]
Rollup really needs stuff like `webpack-dev-server` and `html-webpack-plugin` :D

**Comment by theChesCat** [comment]
(Or you need to use Webpack :trollface: )

**Comment by thoragio** [comment]
@BenoitZugmeyer Thanks for the tutorial with 3 examples today. I think you thoroughly answered my original question which was the title of this issue: how to run a dev server! 🙌

**Comment by BenoitZugmeyer** [comment]
Ah, no problem! FYI I finally use Webpack (but with Rollup behind) to simplify and standardize the build process and dev tools. Watching files is not ideal right now, but I made a PR to rollup-loader to improve this, cf https://github.com/egoist/rollup-loader/pull/11

**Comment by thoragio** [comment]
Awesome! It's already been merged earlier this morning. 💨
